# Generated by Django 4.2.11 on 2025-04-23 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensatoryleaverequest',
            name='leave_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leave.leavetype', verbose_name='Leave type'),
        ),
        migrations.AlterField(
            model_name='compensatoryleaverequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcompensatoryleaverequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalleaveallocationrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='leaveallocationrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=30),
        ),
    ]
