# Generated by Django 4.2.11 on 2025-05-16 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_company_is_notified_access'),
        ('leave', '0002_alter_compensatoryleaverequest_leave_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='company_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_type_company', to='base.company'),
        ),
    ]
