# Generated by Django 4.2.11 on 2025-04-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('re_open', 'Re-Open'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('resolved', 'Resolved'), ('canceled', 'Canceled')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('re_open', 'Re-Open'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('resolved', 'Resolved'), ('canceled', 'Canceled')], default='new', max_length=50),
        ),
    ]
