# Generated by Django 4.2.11 on 2025-05-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_historicalticket_frequency_ticket_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='frequency',
            field=models.CharField(choices=[('select', 'Select Frequency'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='select', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='frequency',
            field=models.CharField(choices=[('select', 'Select Frequency'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='select', max_length=50),
        ),
    ]
