# Generated by Django 4.2.11 on 2025-05-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_alter_historicalticket_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='last_executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='next_execution_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='next_execution_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
