# Generated by Django 4.2.11 on 2025-06-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_company_icon'),
        ('helpdesk', '0008_historicalticket_last_executed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.company'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
