# Generated by Django 4.2.11 on 2025-06-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0009_alter_tickettype_company_id_alter_tickettype_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='prefix',
            field=models.CharField(max_length=3),
        ),
    ]
