# Generated by Django 4.2.11 on 2025-06-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0010_alter_tickettype_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='cron_expression',
            field=models.CharField(blank=True, help_text="CRON expression (e.g. '0 9 * * 1-5' for 9 AM on weekdays)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cron_expression',
            field=models.CharField(blank=True, help_text="CRON expression (e.g. '0 9 * * 1-5' for 9 AM on weekdays)", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='frequency',
            field=models.CharField(choices=[('select', 'Select Frequency'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom CRON')], default='select', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='frequency',
            field=models.CharField(choices=[('select', 'Select Frequency'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom CRON')], default='select', max_length=50),
        ),
    ]
