# Generated by Django 4.2.11 on 2025-03-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='timezone',
            field=models.CharField(default='UTC', max_length=255),
        ),
    ]
