# Generated by Django 4.2.11 on 2025-05-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='onboarding_email_to_employee',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Send onboarding email to employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='welcome_email_to_company',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Send welcome email to entire company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='welcome_email_to_employee',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Send welcome email to employee'),
        ),
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='attachment',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='employee/discipline'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_profile',
            field=models.ImageField(blank=True, help_text='This will be synced with FileStorage', max_length=1000, null=True, upload_to='employee/profile'),
        ),
        migrations.AlterField(
            model_name='policymultiplefile',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='employee/policies', verbose_name='Policy Attachment'),
        ),
    ]
