# Generated by Django 4.2.11 on 2025-05-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_onboarding_email_to_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='onboarding_email_to_employee',
            new_name='send_onboarding_email_to_employee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='welcome_email_to_company',
            new_name='send_welcome_email_to_company',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='welcome_email_to_employee',
            new_name='send_welcome_email_to_employee',
        ),
    ]
