# Generated by Django 4.2.11 on 2025-07-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_documenso_documents_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='wise_recipient_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
