# Generated by Django 4.2.11 on 2025-07-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employee_wise_recipient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='iban',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
