# Generated by Django 4.2.11 on 2025-04-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollsettings',
            name='currency_symbol',
            field=models.CharField(choices=[('INR (₹)', 'INR'), ('USD ($)', 'USD'), ('EUR (€)', 'EUR'), ('GBP (£)', 'GBP'), ('JPY (¥)', 'JPY'), ('PKR (₨)', 'PKR'), ('CHF (₣)', 'CHF'), ('TRY (₺)', 'TRY'), ('PHP (₱)', 'PHP'), ('PYG (₲)', 'PYG'), ('UAH (₴)', 'UAH'), ('CRC (₡)', 'CRC'), ('CDF (₣)', 'CDF'), ('BYN (₴)', 'BYN'), ('LAK (₭)', 'LAK'), ('MNT (₮)', 'MNT'), ('LKR (₨)', 'LKR'), ('ZAR (R)', 'ZAR'), ('AUD ($)', 'AUD'), ('CAD ($)', 'CAD'), ('CNY (¥)', 'CNY'), ('KRW (₩)', 'KRW'), ('SEK (kr)', 'SEK'), ('NOK (kr)', 'NOK'), ('DKK (kr)', 'DKK'), ('PLN (zł)', 'PLN'), ('THB (฿)', 'THB'), ('VND (₫)', 'VND')], default='PKR (₨)', max_length=15, null=True),
        ),
    ]
