# Generated by Django 4.2.11 on 2025-04-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payrollsettings_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxbracket',
            name='base_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Base Value'),
        ),
    ]
