# Generated by Django 4.2.11 on 2025-04-18 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_company_email'),
        ('payroll', '0004_alter_taxbracket_base_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipAutomationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automation_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_company_instance', to='base.company')),
            ],
        ),
    ]
