# Generated by Django 4.2.11 on 2025-04-18 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_alter_payslipautomationemail_automation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslipautomationemail',
            old_name='automation_date',
            new_name='scheduler_date',
        ),
        migrations.RenameField(
            model_name='payslipautomationemail',
            old_name='is_active',
            new_name='scheduler_status',
        ),
        migrations.AddField(
            model_name='payslipautomationemail',
            name='scheduler_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Time of the day when payslip automation should run'),
        ),
    ]
