# Generated by Django 4.2.11 on 2025-04-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_rename_automation_date_payslipautomationemail_scheduler_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslipautomationemail',
            name='scheduler_date',
            field=models.CharField(choices=[('last day', 'Last Day'), ('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th'), ('7', '7th'), ('8', '8th'), ('9', '9th'), ('10', '10th'), ('11', '11th'), ('12', '12th'), ('13', '13th'), ('14', '14th'), ('15', '15th'), ('16', '16th'), ('17', '17th'), ('18', '18th'), ('19', '19th'), ('20', '20th'), ('21', '21th'), ('22', '22th'), ('23', '23th'), ('24', '24th'), ('25', '25th'), ('26', '26th'), ('27', '27th'), ('28', '28th'), ('29', '29th'), ('30', '30th'), ('31', '31th')], default='1', help_text='On this day of every month,Payslip will automatically sent to employees via emails whose payslips will be paid', max_length=30, verbose_name='Email Scheduler Date'),
        ),
    ]
