# Generated by Django 4.2.11 on 2025-04-18 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_alter_payslipautomationemail_scheduler_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslipautomationemail',
            name='scheduler_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Time of the day when payslip automation should run'),
        ),
    ]
