# Generated by Django 4.2.11 on 2025-04-21 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_payslipautomationemail_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslipautomationemail',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='payslipautomationemail',
            name='scheduler_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Time of the day when payslip scheduler should run', verbose_name='Email Scheduler Time'),
        ),
    ]
