# Generated by Django 4.2.11 on 2025-05-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_remove_payslipautomationemail_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='is_multiple_allowance',
            field=models.BooleanField(default=False, editable=False, verbose_name='Recurring Allowance'),
        ),
    ]
