# Generated by Django 4.2.11 on 2025-07-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_allowance_is_multiple_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='is_multiple_deduction',
            field=models.BooleanField(default=False, help_text='To specify, the deduction is Recurssive or not', verbose_name='Recurring Deduction'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_document',
            field=models.FileField(blank=True, null=True, upload_to='contract_documents/'),
        ),
    ]
