# Generated by Django 4.2.11 on 2025-05-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintegration',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='integration_images/'),
        ),
    ]
