# Generated by Django 4.2.11 on 2025-05-05 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_companyintegration_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyintegration',
            options={'permissions': [('can_connect_service', 'Can connect to integration services'), ('can_disconnect_service', 'Can disconnect to integration services'), ('can_update_service', 'Can update to integration services'), ('can_create_service', 'Can add to integration services')]},
        ),
    ]
