# Generated by Django 4.2.11 on 2025-05-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_alter_companyintegration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintegration',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='redirect_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
