# Generated by Django 4.2.11 on 2025-05-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_companyintegration_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintegration',
            name='auth_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
