# Generated by Django 4.2.11 on 2025-05-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_companyintegration_auth_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintegration',
            name='scopes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
