# Generated by Django 4.2.11 on 2025-05-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_companyintegration_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintegration',
            name='channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
