# Generated by Django 4.2.11 on 2025-05-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_companyintegration_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintegration',
            name='is_attendance_integration',
            field=models.BooleanField(default=False, verbose_name='Attendance Tracking'),
        ),
    ]
