# Generated by Django 4.2.11 on 2025-05-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_companyintegration_is_attendance_integration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyintegration',
            name='is_attendance_integration',
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='send_attendance_notifications',
            field=models.BooleanField(default=False, verbose_name='Attendance Notifications'),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='send_birthday_notifications',
            field=models.BooleanField(default=False, verbose_name='Birthday Notifications'),
        ),
    ]
