# Generated by Django 4.2.11 on 2025-05-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_remove_companyintegration_is_attendance_integration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintegration',
            name='is_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='selected_bot_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='selected_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyintegration',
            name='service',
            field=models.CharField(choices=[('slack', 'Slack')], default='slack', max_length=50),
        ),
    ]
