# Generated by Django 4.2.11 on 2025-05-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_company_icon'),
        ('integrations', '0011_remove_companyintegration_is_configured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyintegration',
            name='company',
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, related_name='integrations', to='base.company'),
        ),
    ]
