# Generated by Django 4.2.11 on 2025-05-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_alter_companyintegration_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableintegration',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
