# Generated by Django 4.2.11 on 2025-06-03 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_remove_companyintegration_company_and_more'),
        ('integrations', '0013_alter_availableintegration_name'),
    ]

    operations = [
    ]
