# Generated by Django 4.2.11 on 2025-06-12 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_company_icon'),
        ('integrations', '0014_merge_20250603_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintegration',
            name='documenso_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Documenso API Key'),
        ),
    ]
