# Generated by Django 4.2.11 on 2025-07-15 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_company_icon'),
        ('integrations', '0016_remove_companyintegration_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintegration',
            name='documenso_notification_message',
            field=models.TextField(blank=True, null=True, verbose_name='Documenso Document Notification Message'),
        ),
    ]
