# Generated by Django 4.2.11 on 2025-07-16 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_company_icon'),
        ('integrations', '0017_companyintegration_documenso_notification_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintegration',
            name='documenso_processing_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Documenso Processing Hours'),
        ),
    ]
