# Generated by Django 4.2.11 on 2025-07-17 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_company_icon'),
        ('integrations', '0018_companyintegration_documenso_processing_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintegration',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
