# Generated by Django 4.2.11 on 2025-07-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_company_icon'),
        ('integrations', '0019_companyintegration_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintegration',
            name='wise_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wise API Key'),
        ),
    ]
