# Generated by Django 4.2.11 on 2025-07-22 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_company_icon'),
        ('payroll', '0015_deduction_is_multiple_deduction_and_more'),
        ('employee', '0009_employee_iban'),
        ('integrations', '0021_remove_companyintegration_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeewiserecipient',
            name='transfer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeewiserecipient',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wise_recipient_employee', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employeewiserecipient',
            name='payslip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wise_recipient_payslip', to='payroll.payslip'),
        ),
    ]
