# Generated by Django 4.2.11 on 2025-02-28 13:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='new', max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='project/files', verbose_name='Project File')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('managers', models.ManyToManyField(blank=True, related_name='project_managers', to='employee.employee', verbose_name='Project Managers')),
                ('members', models.ManyToManyField(blank=True, related_name='project_members', to='employee.employee', verbose_name='Project Members')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sequence', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_end_stage', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_stages', to='project.project')),
            ],
            options={
                'unique_together': {('project', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='to_do', max_length=250)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='task/files', verbose_name='Task File')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('sequence', models.IntegerField(default=0)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.projectstage', verbose_name='Project Stage')),
                ('task_managers', models.ManyToManyField(blank=True, to='employee.employee', verbose_name='Task Managers')),
                ('task_members', models.ManyToManyField(blank=True, related_name='tasks', to='employee.employee', verbose_name='Task Members')),
            ],
            options={
                'unique_together': {('project', 'title')},
            },
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time_spent', models.CharField(default='00:00', max_length=10, null=True, validators=[project.models.validate_time_format], verbose_name='Hours Spent')),
                ('status', models.CharField(choices=[('in_Progress', 'In Progress'), ('completed', 'Completed')], default='in_Progress', max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_timesheet', to='project.project', verbose_name='Project')),
                ('task_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_timesheet', to='project.task', verbose_name='Task')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
