# Generated by Django 4.2.11 on 2025-05-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_company_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_notified_access',
            field=models.BooleanField(default=False),
        ),
    ]
