# Generated by Django 4.2.11 on 2025-05-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_company_is_notified_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_notified_access',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
