# Generated by Django 4.2.11 on 2025-05-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_company_is_notified_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='icon',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='base/icon'),
        ),
    ]
